function plot_data(XData1, YData1, YData2, YData3, YData4)
%CREATEFIGURE(XData1, YData1, YData2, YData3, Parent1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 03-Nov-2021 11:11:04

% Create figure
figure('Tag','ScopePrintToFigure','Color',[1 1 1],...
    'OuterPosition',[481.8 192.6 574.4 486]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag',...
    'Position',[0.0447154480438379 0.0449628135334245 0.937350549086722 0.929682216892539]);
hold(axes1,'on');
colororder([0 0.447058823529412 0.741176470588235;0.850980392156863 0.325490196078431 0.0980392156862745;0.929411764705882 0.694117647058824 0.125490196078431;0.494117647058824 0.184313725490196 0.556862745098039;0.466666666666667 0.674509803921569 0.188235294117647;0.301960784313725 0.745098039215686 0.933333333333333;0.635294117647059 0.0784313725490196 0.184313725490196]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','LMPCF','Tag','DisplayLine1','LineWidth',3,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create line
line(XData1,YData2,'DisplayName','BSMCF','Tag','DisplayLine2','LineWidth',3,...
    'LineStyle','--',...
    'Color',[1 0 0]);

% Create line
line(XData1,YData3,'DisplayName','LMPC','Tag','DisplayLine3','LineWidth',3,...
    'LineStyle','-.',...
    'Color',[0.423529411764706 0.250980392156863 0.392156862745098]);

 line(XData1,YData4,'DisplayName','SP','Tag','DisplayLine4','LineWidth',3,...
      'LineStyle','-.',...
     'Color',[0.466666666666667 0.674509803921569 0.188235294117647]);

% Create xlabel
xlabel(' ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.423423169081759 0.637913189546471]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','GridAlpha',0.4,'GridColor',[0 0 0],...
    'TickLabelInterpreter','none','XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels',...
    'Position',[460.13333243688 18.9332945777697 88.6000008964539 45.8000009727478],...
    'Interpreter','none',...
    'FontSize',8,...
    'EdgeColor',[0 0 0]);

